# -*- coding: utf-8 -*-
"""inClassAssignment5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3MeEiovBmJLM6Htyd2qps_zVcl7Va9D
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Title of the web app
st.title("Interactive Streamlit Web App")

# Sidebar for inputs
st.sidebar.header("User Input Section")

# Sidebar widgets for user input
name = st.sidebar.text_input("Enter your name", "John Doe")
age = st.sidebar.slider("Select your age", 18, 100, 25)
hobby = st.sidebar.selectbox("What's your favorite hobby?", ['Reading', 'Sports', 'Music', 'Traveling', 'Coding'])

# Display the input information
st.subheader("User Information")
st.write(f"Hello **{name}**, you are **{age}** years old and your favorite hobby is **{hobby}**.")


# Interactive number input and display
st.subheader("Interactive Number Input")
num = st.number_input('Enter a number', 0, 100, 50)
st.write(f"You entered the number: **{num}**")