# -*- coding: utf-8 -*-
"""inClassAssignment5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3MeEiovBmJLM6Htyd2qps_zVcl7Va9D
"""

! pip install streamlit

import streamlit as st

# Set up the page layout
st.set_page_config(page_title="Background Color Changer", layout="wide")

# Title of the web app
st.title("Interactive Background Color Changer")

# Sidebar for user input
st.sidebar.header("Customize Background Color")

# Use the color picker to allow users to pick a color
color = st.sidebar.color_picker('Pick a background color', '#FFFFFF')

# Set the background color using custom CSS
page_bg_color = f"""
    <style>
    .stApp {{
        background-color: {color};
    }}
    </style>
    """
st.markdown(page_bg_color, unsafe_allow_html=True)

# Display the chosen color in the main page
st.subheader(f"Your selected color: {color}")

# Other interactive elements (optional)
st.write("Use the color picker on the sidebar to change the background color dynamically.")